DECLARE
V_COUNT INTEGER;
BEGIN
SELECT COUNT(TABLE_NAME) INTO V_COUNT from USER_TABLES where TABLE_NAME = '__EFMigrationsHistory';
IF V_COUNT = 0 THEN
Begin
BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"__EFMigrationsHistory" (
    "MigrationId" NVARCHAR2(150) NOT NULL,
    "ProductVersion" NVARCHAR2(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
)';
END;

End;

END IF;
EXCEPTION
WHEN OTHERS THEN
    IF(SQLCODE != -942)THEN
        RAISE;
    END IF;
END;
/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260915193508_first_migrations';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "AspNetRoles" (
        "Id" RAW(16) NOT NULL,
        "Name" NVARCHAR2(256),
        "NormalizedName" NVARCHAR2(256),
        "ConcurrencyStamp" NVARCHAR2(2000),
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260915193508_first_migrations';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "AspNetUsers" (
        "Id" RAW(16) NOT NULL,
        "FirstName" NVARCHAR2(2000) NOT NULL,
        "LastName" NVARCHAR2(2000),
        "Birthday" TIMESTAMP(7),
        "Active" BOOLEAN NOT NULL,
        "CreatedAt" TIMESTAMP(7) NOT NULL,
        "LastUpdatedAt" TIMESTAMP(7),
        "UserName" NVARCHAR2(256),
        "NormalizedUserName" NVARCHAR2(256),
        "Email" NVARCHAR2(256),
        "NormalizedEmail" NVARCHAR2(256),
        "EmailConfirmed" BOOLEAN NOT NULL,
        "PasswordHash" NVARCHAR2(2000),
        "SecurityStamp" NVARCHAR2(2000),
        "ConcurrencyStamp" NVARCHAR2(2000),
        "PhoneNumber" NVARCHAR2(2000),
        "PhoneNumberConfirmed" BOOLEAN NOT NULL,
        "TwoFactorEnabled" BOOLEAN NOT NULL,
        "LockoutEnd" TIMESTAMP(7) WITH TIME ZONE,
        "LockoutEnabled" BOOLEAN NOT NULL,
        "AccessFailedCount" NUMBER(10) NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260915193508_first_migrations';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "AspNetRoleClaims" (
        "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
        "RoleId" RAW(16) NOT NULL,
        "ClaimType" NVARCHAR2(2000),
        "ClaimValue" NVARCHAR2(2000),
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260915193508_first_migrations';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "AspNetUserClaims" (
        "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
        "UserId" RAW(16) NOT NULL,
        "ClaimType" NVARCHAR2(2000),
        "ClaimValue" NVARCHAR2(2000),
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260915193508_first_migrations';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "AspNetUserLogins" (
        "LoginProvider" NVARCHAR2(450) NOT NULL,
        "ProviderKey" NVARCHAR2(450) NOT NULL,
        "ProviderDisplayName" NVARCHAR2(2000),
        "UserId" RAW(16) NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260915193508_first_migrations';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "AspNetUserRoles" (
        "UserId" RAW(16) NOT NULL,
        "RoleId" RAW(16) NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260915193508_first_migrations';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "AspNetUserTokens" (
        "UserId" RAW(16) NOT NULL,
        "LoginProvider" NVARCHAR2(450) NOT NULL,
        "Name" NVARCHAR2(450) NOT NULL,
        "Value" NVARCHAR2(2000),
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260915193508_first_migrations';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260915193508_first_migrations';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260915193508_first_migrations';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260915193508_first_migrations';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260915193508_first_migrations';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260915193508_first_migrations';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260915193508_first_migrations';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260915193508_first_migrations';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES (N''20260915193508_first_migrations'', N''10.0.12'')'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260916194301_add_home_entity';
IF v_Count = 0 THEN

    declare
       l_nullable user_tab_columns.nullable % type;
    begin 
       select nullable into l_nullable 
       from user_tab_columns 
      where table_name = 'AspNetUsers' 
      and column_name = 'LastName' 
    ;
       if l_nullable = 'N' then 
            EXECUTE IMMEDIATE 'ALTER TABLE "AspNetUsers" MODIFY "LastName" NVARCHAR2(30) NULL';
     else 
            EXECUTE IMMEDIATE 'ALTER TABLE "AspNetUsers" MODIFY "LastName" NVARCHAR2(30)';
     end if;
    end;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260916194301_add_home_entity';
IF v_Count = 0 THEN

    declare
       l_nullable user_tab_columns.nullable % type;
    begin 
       select nullable into l_nullable 
       from user_tab_columns 
      where table_name = 'AspNetUsers' 
      and column_name = 'FirstName' 
    ;
       if l_nullable = 'N' then 
            EXECUTE IMMEDIATE 'ALTER TABLE "AspNetUsers" MODIFY "FirstName" NVARCHAR2(50) ';
     else 
            EXECUTE IMMEDIATE 'ALTER TABLE "AspNetUsers" MODIFY "FirstName" NVARCHAR2(50) NOT NULL';
     end if;
    end;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260916194301_add_home_entity';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "Homes" (
        "Id" RAW(16) NOT NULL,
        "Name" NVARCHAR2(150) NOT NULL,
        "ZipCode" NVARCHAR2(8),
        "Address" NVARCHAR2(150),
        "AddressNumber" NUMBER(10),
        "UserId" RAW(16) NOT NULL,
        "CreatedAt" TIMESTAMP(7) NOT NULL,
        "LastUpdatedAt" TIMESTAMP(7),
        CONSTRAINT "PK_Homes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Homes_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260916194301_add_home_entity';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_Homes_UserId" ON "Homes" ("UserId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260916194301_add_home_entity';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES (N''20260916194301_add_home_entity'', N''10.0.12'')'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260917143759_add_family_and_shared_home';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'ALTER TABLE "Homes" ADD "FamilyId" RAW(16)'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260917143759_add_family_and_shared_home';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "Families" (
        "Id" RAW(16) NOT NULL,
        "Name" NVARCHAR2(150) NOT NULL,
        "CreatedAt" TIMESTAMP(7) NOT NULL,
        "LastUpdatedAt" TIMESTAMP(7),
        CONSTRAINT "PK_Families" PRIMARY KEY ("Id")
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260917143759_add_family_and_shared_home';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "UserFamilies" (
        "Id" RAW(16) NOT NULL,
        "FamilyId" RAW(16) NOT NULL,
        "CreatedAt" TIMESTAMP(7) NOT NULL,
        "LastUpdatedAt" TIMESTAMP(7),
        "UserId" RAW(16) NOT NULL,
        CONSTRAINT "PK_UserFamilies" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserFamilies_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserFamilies_Families_FamilyId" FOREIGN KEY ("FamilyId") REFERENCES "Families" ("Id") ON DELETE CASCADE
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260917143759_add_family_and_shared_home';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_Homes_FamilyId" ON "Homes" ("FamilyId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260917143759_add_family_and_shared_home';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_UserFamilies_FamilyId" ON "UserFamilies" ("FamilyId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260917143759_add_family_and_shared_home';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE UNIQUE INDEX "IX_UserFamilies_UserId_FamilyId" ON "UserFamilies" ("UserId", "FamilyId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260917143759_add_family_and_shared_home';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'ALTER TABLE "Homes" ADD CONSTRAINT "FK_Homes_Families_FamilyId" FOREIGN KEY ("FamilyId") REFERENCES "Families" ("Id") ON DELETE SET NULL'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260917143759_add_family_and_shared_home';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES (N''20260917143759_add_family_and_shared_home'', N''10.0.12'')'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260917193630_add_family_titles_and_membership_role';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'ALTER TABLE "UserFamilies" ADD "FamilyTitleId" RAW(16)'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260917193630_add_family_titles_and_membership_role';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'ALTER TABLE "UserFamilies" ADD "Role" NVARCHAR2(20) DEFAULT N''Member'' NOT NULL'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260917193630_add_family_titles_and_membership_role';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "FamilyTitles" (
        "Id" RAW(16) NOT NULL,
        "Name" NVARCHAR2(50) NOT NULL,
        "FamilyId" RAW(16),
        "CreatedAt" TIMESTAMP(7) NOT NULL,
        "LastUpdatedAt" TIMESTAMP(7),
        CONSTRAINT "PK_FamilyTitles" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FamilyTitles_Families_FamilyId" FOREIGN KEY ("FamilyId") REFERENCES "Families" ("Id") ON DELETE CASCADE
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260917193630_add_family_titles_and_membership_role';
IF v_Count = 0 THEN

    BEGIN
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000001'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Pai');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000002'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Mãe');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000003'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Cônjuge');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000004'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Filho');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000005'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Filha');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000006'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Irmão');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000007'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Irmã');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000008'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Avô');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000009'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Avó');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000010'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Neto');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000011'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Neta');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000012'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Tio');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000013'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Tia');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000014'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Sobrinho');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000015'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Sobrinha');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000016'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Primo');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000017'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Prima');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000018'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Padrasto');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000019'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Madrasta');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000020'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Enteado');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000021'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Enteada');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000022'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Sogro');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000023'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Sogra');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000024'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Genro');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000025'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Nora');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000026'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Cunhado');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000027'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Cunhada');
    INSERT INTO "FamilyTitles" ("Id", "CreatedAt", "FamilyId", "LastUpdatedAt", "Name")
    VALUES (HEXTORAW('D4C3B2A1000000408000000000000028'), TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL, N'Agregado');
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260917193630_add_family_titles_and_membership_role';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_UserFamilies_FamilyTitleId" ON "UserFamilies" ("FamilyTitleId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260917193630_add_family_titles_and_membership_role';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE UNIQUE INDEX "IX_FamilyTitles_FamilyId_Name" ON "FamilyTitles" ("FamilyId", "Name")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260917193630_add_family_titles_and_membership_role';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'ALTER TABLE "UserFamilies" ADD CONSTRAINT "FK_UserFamilies_FamilyTitles_FamilyTitleId" FOREIGN KEY ("FamilyTitleId") REFERENCES "FamilyTitles" ("Id") ON DELETE SET NULL'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260917193630_add_family_titles_and_membership_role';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES (N''20260917193630_add_family_titles_and_membership_role'', N''10.0.12'')'
    ;
 END IF;
END;

/

